### ISSUE TITLE
一直提示COOKIE报错怎么办

### ISSUE THREAD

**Issue by JamYiz** [xjasonlyu/98tang_daysign#1]
请问是我的获取方式不对吗？还是格式问题？
cPNj_123_saltkey=123; 
cPNj_123_auth=321；
大概这样排列了几行是正确的吗？

**Comment by xjasonlyu** [comment]
一行，不要分行试试

**Comment by JamYiz** [comment]
仍然异常，我复制的是https://www.sehuatang.net/plugin.php?id=dd_sign&view=daysign此处的cookie，提取后将 -H "cookie:引号内的内容复制到COOKIE中，是我的操作有问题吗老哥😥

**Comment by xjasonlyu** [comment]
🤔不清楚具体发现了啥

**Comment by JamYiz** [comment]
解决了，感谢🤣
