### ISSUE TITLE
青龙报错'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by JamYiz** [xjasonlyu/98tang_daysign#10]
错误原因：'NoneType' object is not subscriptable
tg 服务启动
tg 推送成功！

![图片](https://user-images.githubusercontent.com/44351690/166690535-637b4739-8b6c-4003-9620-c8447962d904.png)
填写应该没有错误

**Comment by JamYiz** [comment]
![图片](https://user-images.githubusercontent.com/44351690/166694109-8b3e6909-5d0c-45f2-b6ba-6ce3f911670d.png)

**Comment by yelc66** [comment]
解决了嘛，我也碰到这个问题了

**Comment by JamYiz** [comment]
> 解决了嘛，我也碰到这个问题了

可能是复制错请求了
