### ISSUE TITLE
青龙报错 ModuleNotFoundError: No module named 'uncurl'

### ISSUE THREAD

**Issue by uJZk** [xjasonlyu/98tang_daysign#11]
Traceback (most recent call last):
  File "/ql/data/scripts/xjasonlyu_98tang_daysign/daysign.py", line 4, in <module>
    import uncurl
ModuleNotFoundError: No module named 'uncurl'

**Comment by hechuan4** [comment]
同问,,请问你怎么解决的

**Comment by uJZk** [comment]
> 同问,,请问你怎么解决的

没能解决

**Comment by hechuan4** [comment]
> > 同问,,请问你怎么解决的
> 
> 不能解决

我用别的工具解决了.
https://github.com/qiandao-today/qiandao
https://github.com/qiandao-today/templates
(这里里面的98.har 需要编辑器打开改一下域名.就能用了)
https://github.com//wjf0214/qd-templates/

**Comment by uJZk** [comment]
> > > 同问,,请问你怎么解决的
> > 
> > 
> > 不能解决
> 
> 我用别的工具解决了. https://github.com/qiandao-today/qiandao https://github.com/qiandao-today/templates (这里里面的98.har 需要编辑器打开改一下域名.就能用了) https://github.com//wjf0214/qd-templates/

这个方案可以，我的问题解决了
