### ISSUE TITLE
论坛改版了，加了个年龄验证，导致脚本失效

### ISSUE THREAD

**Issue by tyhunter** [xjasonlyu/98tang_daysign#13]
现在签到会提示：
错误原因：'NoneType' object is not subscriptable

辛苦大佬修复更新

**Comment by xjasonlyu** [comment]
cookies过期了，重新获取一下就行了。

**Comment by tyhunter** [comment]
> cookies过期了，重新获取一下就行了。

感谢，确实是，现在可以了
