### ISSUE TITLE
现在必须回一次贴才能签到了，有时间解决一下吗？

### ISSUE THREAD

**Issue by GHang9** [xjasonlyu/98tang_daysign#15]
错误原因：'NoneType' object is not subscriptable
请至少发表或回复一个帖子后再来签到
![1](https://github.com/xjasonlyu/98tang_daysign/assets/94511556/198e380b-716c-48e4-aba8-2d135a666cb2)
![2](https://github.com/xjasonlyu/98tang_daysign/assets/94511556/1e5ae643-8ff2-4284-a9ae-5b031ffce605)

**Comment by super-upup** [comment]
可以用这个https://github.com/super-upup/98tang

**Comment by GHang9** [comment]
> 可以用这个https://github.com/super-upup/98tang

额，你这个不敢用

**Comment by Jieoz** [comment]
同求大佬

**Comment by xjasonlyu** [comment]
过几天我看看有空再修一下。

**Comment by Jieoz** [comment]
> 过几天我看看有空再修一下。

谢谢大佬么么哒

**Comment by xjasonlyu** [comment]
已修复。
