### ISSUE TITLE
签到好像又更新了，抽空看看有没有时间更新一下脚本

### ISSUE THREAD

**Issue by GHang9** [xjasonlyu/98tang_daysign#17]
签到好像又更新了，现在又不能用了
![屏幕截图 2024-01-19 094041.png](https://pic.ziyuan.wang/user/guest/2024/01/ 2024-01-19 094041_cb756d6cd8870.png)
![Uploading 屏幕截图 2024-01-19 094041.png…]()

**Comment by GHang9** [comment]
<img src="https://pic.ziyuan.wang/user/guest/2024/01/ 2024-01-19 094041_cb756d6cd8870.png" alt="屏幕截图 2024-01-19 094041.png" title="屏幕截图 2024-01-19 094041.png" />

**Comment by xjasonlyu** [comment]
今天已经更新修复过了

**Comment by GHang9** [comment]
> 今天已经更新修复过了

给力
