### ISSUE TITLE
兄弟们，脚本还能用吗？

### ISSUE THREAD

**Issue by xueli12** [xjasonlyu/98tang_daysign#19]
我拿源码修改后运行后已经是这样的，想问问大伙是我的问题还是原来的脚本已经不能用了？
![image](https://github.com/xjasonlyu/98tang_daysign/assets/51438016/77982771-78e7-47d2-bc52-e1c136588532)

**Comment by xjasonlyu** [comment]
能用，每天签到都没问题。

**Comment by xueli12** [comment]
> 能用，每天签到都没问题。

噢，看来是我的问题了，谢谢
