### ISSUE TITLE
脚本又不能用了吗

### ISSUE THREAD

**Issue by GHang9** [xjasonlyu/98tang_daysign#27]
错误原因：403 Client Error: Forbidden for url: https://www.sehuatang.net/forum.php?mod=forumdisplay&fid=103
tg 服务的 bot_token 或者 user_id 未设置!!
![](https://b2r.aiyongaiwan.com/imgs/2024/05/25/dce93523d7eb8291.png)

**Comment by xjasonlyu** [comment]
你得更新一下脚本先

**Comment by GHang9** [comment]
> 你得更新一下脚本先

可以用了，感谢作者

**Comment by Jieoz** [comment]
> > 你得更新一下脚本先
> 
> 可以用了，感谢作者

大佬求教flareSolverr 容器要怎么让脚本引用到呢
