### ISSUE TITLE
大佬求教 青龙中要如何使用FlareSolverr

### ISSUE THREAD

**Issue by Jieoz** [xjasonlyu/98tang_daysign#29]
查了一天了毫无进展，网上找不到可用的教程，我是docker青龙和docker FlareSolverr，问ai好像也只能合并两个docker镜像。
可这我怎么操作得了😭
我还是arm版的主机，直接也不能安装FlareSolverr二进制文件

**Comment by xjasonlyu** [comment]
直接两个分别安装不就好了

**Comment by Jieoz** [comment]
> 直接两个分别安装不就好了

意思是不用docker吗大佬，FlareSolverr没有arm64二进制文件。

只能换x86环境了吗，我还以为用docker版本的人多呢

**Comment by xjasonlyu** [comment]
都用docker不行吗，compose管理一下

**Comment by Jieoz** [comment]
> 都用docker不行吗，compose管理一下

谢谢大佬，解决了compose昨天查Google问ai都没弄了，没看到项目里还有一个flaresolverr.py，加到青龙里就好了。
把事情弄复杂了
