### ISSUE TITLE
你好这个可以推荐到青龙面板里面定时跑嘛

### ISSUE THREAD

**Issue by yelc66** [xjasonlyu/98tang_daysign#3]
11

**Comment by xjasonlyu** [comment]
你好，我不知道那是什么，但是只要遵守开源协议即可。

**Comment by lancer-wang** [comment]
我试了一下是可以的,多谢提醒
![image](https://user-images.githubusercontent.com/69783837/147518335-b279c573-05a9-4216-8f1d-0fd374dabd5d.png)

**Comment by lancer-wang** [comment]
> 你好，我不知道那是什么，但是只要遵守开源协议即可。

青龙就是一个批量管理/执行计划任务的平台

**Comment by yelc66** [comment]
> 我试一下是可以的，多谢提醒 ![图片](https://user-images.githubusercontent.com/69783837/147518335-b279c573-05a9-4216-8f1d-0fd374dabd5d.png)

方便加个联系方式，我对青龙的环境变量设置不懂，想看看您的是怎么设置的
