### ISSUE TITLE
Qinglong失败

### ISSUE THREAD

**Issue by Khaleesi01** [xjasonlyu/98tang_daysign#7]
## 开始执行... 2022-04-15 12:05:31

/ql/config/env.sh: line 18: syntax error near unexpected token `('
/ql/config/env.sh: line 18: `-H'user-agent:Mozilla/5.0(WindowsNT10.0;Win64;x64)AppleWebKit/537.36(KHTML,likeGecko)Chrome/100.0.4896.75Safari/537.36'\'
/ql/config/env.sh: line 18: syntax error near unexpected token `('
/ql/config/env.sh: line 18: `-H'user-agent:Mozilla/5.0(WindowsNT10.0;Win64;x64)AppleWebKit/537.36(KHTML,likeGecko)Chrome/100.0.4896.75Safari/537.36'\'
<b>98堂 签到异常</b>

错误原因：'NoneType' object is not subscriptable
--------------------
None

## 执行结束... 2022-04-15 12:05:32 耗时 1 秒

**Comment by xjasonlyu** [comment]
复制copy as nodejs fetch，添加FETCH环境变量，CURL在青龙里用有bug

**Comment by Khaleesi01** [comment]
> 
换成FETCH后，task xx/daysign.py 这样
## 开始执行... 2022-04-15 12:28:54

Traceback (most recent call last):
  File "/ql/scripts/daysign.py", line 135, in <module>
    main()
  File "/ql/scripts/daysign.py", line 103, in main
    cookies = retrieve_cookies_from_fetch('FETCH')
  File "/ql/scripts/daysign.py", line 78, in retrieve_cookies_from_fetch
    cookie_str = parse_fetch(os.getenv(env))['headers']['cookie']
  File "/ql/scripts/daysign.py", line 73, in parse_fetch
    exec(s, {
  File "<string>", line 20
    });;
       ^
SyntaxError: invalid syntax

## 执行结束... 2022-04-15 12:28:54 耗时 0 秒

**Comment by xjasonlyu** [comment]
你fetch格式没粘贴对？你可以把cookie脱敏一下粘贴上来看看

**Comment by Khaleesi01** [comment]
> 

fetch("https://www.sehuatang.net/plugin.php?id=dd_sign&view=daysign", {
  "headers": {
    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
    "accept-language": "zh-CN,zh;q=0.9,zh-TW;q=0.8,en-US;q=0.7,en;q=0.6",
    "cache-control": "max-age=0",
    "sec-ch-ua": "\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"100\", \"Google Chrome\";v=\"100\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"Windows\"",
    "sec-fetch-dest": "document",
    "sec-fetch-mode": "navigate",
    "sec-fetch-site": "cross-site",
    "sec-fetch-user": "?1",
    "upgrade-insecure-requests": "1",
    "cookie": "cxxxE9Sw==",
    "Referer": "https://github.com/xjasonlyu/98tang_daysign",
    "Referrer-Policy": "no-referrer-when-downgrade"
  },
  "body": null,
  "method": "GET"
}); ;
fetch("https://www.sehuatang.net/static/image/common/logo.png", {
  "headers": {
    "sec-ch-ua": "\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"100\", \"Google Chrome\";v=\"100\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"Windows\"",
    "Referer": "https://www.sehuatang.net/plugin.php?id=dd_sign&view=daysign",
    "Referrer-Policy": "strict-origin-when-cross-origin"
  },
  "body": null,
  "method": "GET"
}); ;
fetch("https://www.sehuatang.net/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js", {
  "headers": {
    "sec-ch-ua": "\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"100\", \"Google Chrome\";v=\"100\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"Windows\"",
    "Referer": "https://www.sehuatang.net/plugin.php?id=dd_sign&view=daysign",
    "Referrer-Policy": "strict-origin-when-cross-origin"
  },
  "body": null,
  "method": "GET"
}); ;
fetch("https://www.sehuatang.net/uc_server/data/avatar/000/41/96/87_avatar_small.jpg", {
  "headers": {
    "sec-ch-ua": "\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"100\", \"Google Chrome\";v=\"100\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"Windows\"",
    "Referer": "https://www.sehuatang.net/plugin.php?id=dd_sign&view=daysign",
    "Referrer-Policy": "strict-origin-when-cross-origin"
  },
  "body": null,
  "method": "GET"
}); ;
fetch("https://www.sehuatang.net/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js", {
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": null,
  "method": "GET"
}); ;
fetch("https://www.sehuatang.net/template/default/style/t1/background.png", {
  "headers": {
    "sec-ch-ua": "\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"100\", \"Google Chrome\";v=\"100\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"Windows\"",
    "Referer": "https://www.sehuatang.net/template/default/style/t1/style.css",
    "Referrer-Policy": "strict-origin-when-cross-origin"
  },
  "body": null,
  "method": "GET"
}); ;
fetch("https://www.sehuatang.net/template/default/style/t1/bgimg.jpg", {
  "headers": {
    "sec-ch-ua": "\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"100\", \"Google Chrome\";v=\"100\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"Windows\"",
    "Referer": "https://www.sehuatang.net/template/default/style/t1/style.css",
    "Referrer-Policy": "strict-origin-when-cross-origin"
  },
  "body": null,
  "method": "GET"
}); ;
fetch("https://www.sehuatang.net/static/image/common/switch_width.png", {
  "headers": {
    "sec-ch-ua": "\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"100\", \"Google Chrome\";v=\"100\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"Windows\"",
    "Referer": "https://www.sehuatang.net/data/cache/style_1_common.css?JXX",
    "Referrer-Policy": "strict-origin-when-cross-origin"
  },
  "body": null,
  "method": "GET"
}); ;
fetch("https://www.sehuatang.net/static/image/common/switch_style.png", {
  "headers": {
    "sec-ch-ua": "\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"100\", \"Google Chrome\";v=\"100\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"Windows\"",
    "Referer": "https://www.sehuatang.net/data/cache/style_1_common.css?JXX",
    "Referrer-Policy": "strict-origin-when-cross-origin"
  },
  "body": null,
  "method": "GET"
}); ;
fetch("https://www.sehuatang.net/static/js/common.js?JXX", {
  "headers": {
    "sec-ch-ua": "\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"100\", \"Google Chrome\";v=\"100\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"Windows\"",
    "Referer": "https://www.sehuatang.net/plugin.php?id=dd_sign&view=daysign",
    "Referrer-Policy": "strict-origin-when-cross-origin"
  },
  "body": null,
  "method": "GET"
}); ;
fetch("https://www.sehuatang.net/static/libs/fingerprintjs/fp.min.js", {
  "headers": {
    "sec-ch-ua": "\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"100\", \"Google Chrome\";v=\"100\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"Windows\"",
    "Referer": "https://www.sehuatang.net/plugin.php?id=dd_sign&view=daysign",
    "Referrer-Policy": "strict-origin-when-cross-origin"
  },
  "body": null,
  "method": "GET"
}); ;
fetch("https://www.sehuatang.net/static/js/language.js", {
  "headers": {
    "sec-ch-ua": "\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"100\", \"Google Chrome\";v=\"100\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"Windows\"",
    "Referer": "https://www.sehuatang.net/plugin.php?id=dd_sign&view=daysign",
    "Referrer-Policy": "strict-origin-when-cross-origin"
  },
  "body": null,
  "method": "GET"
}); ;
fetch("data:application/x-font-woff;charset=utf-8;base64,d09GRgABAAAAAAbAAAsAAAAACgAAAQAAAAAAAAAAXXXXXXF4cAAABSwAAAAfAAAAIAEVAGJuYW1lAAAFTAAAAUUAAAJtPlT+fXBvc3QAAAaUAAAAKwAAAEO1YO5beJxjYGRgYOBikGPQYWB0cfMJYeBgYGGAAJAMY05meiJQDMoDyrGAaQ4gZoOIAgCKIwNPAHicY2Bk/s04gYGVgYOpk+kMAwNDP4RmfM1gxMjBwMDEwMrMgBUEpLmmMDgwVLzYzdzwv4EhhrmBoQEozAiSAwAyXg0seJzFkdEJgDAMRF9sFSmO4hAO5JcguJv7lG6h18YPncALryRHSEsK9EAQs4hgG0bVKteaH0jNjyyqEyOd4sjkvZzXJe+du0x9HjUP6q+zB36T/Xf1V1M7l6fSVjge9MSMU38k7452Rzkd4g2B2RgkAHicbVJNaBNBGJ1vptlsNptMNruzSTZuks2abO3PJtkm20pNf6xa/AH/C4WKCl5bL6IgHiIieFARPCoIIljxIHoULyJ48qLevKhUpAdvHgTtrk5SUSx+M99733d4hzdvUAShnx/JM5JFKupHDbQDHUAIhEEoJ7EJltN08SAwK8IyWpI4tmNF7bJL2pApC5ru+c1qRogKFJJQgBHL8x0XO9BqTuBx8HQTIJc3Dqcrm9LkBkhZp3A53IPvAivam+jEcLh7aFLzSqp4Tk6nc+n0VVGIRESM+2gSFjN6LBKThPBehBrsWXELLoKcc4x984lSPn3ySnPJrGRiAJ0OqPlS8v6kYij8XjB0NZ2LphJi1kjYmzU49ymeVWWzuoJ4CdzrU/KCLKEi2oJ8NIP2o6Pcrc00oVx1WhZLQpftJESVAmSsCRhVXCBJsK1ytaVYFc9vQ7NaFkxu1/q7aDqx2Qhb73Gs8IEcP1QYNCF8DuaQCQcHtgJsHcCPB8YwHouCSoP9VMPfgscSpVr3+R71Bnpz9Smv1WPugkvq06phqNPrCF4lGK94wBm/rDTWvsqplIz1W5J4VpQ2QLhSW6gdc2FnDaE+7vkOeU9OIBs5aBBNdv22mlUesBBlVsuF7mTCRs+WYrX4AX3EG/VHgQddjoLD3WoZsjijUUI1CGdAo5iyXY0pgKkGftfj6NpbMtztUJQSMbGvD/bEVEMKX92WDC2GP89RxujcOsJUPbhd76rq+FR9KojAj72ng+tSBHOVZKgxruqKEer+0w75QDp/sjvyJ7k2WL/5/8k5/ySn6f8kp4JQrkG16XtFUH1P18iZ+VKtFC5zmHfbAG0Xr/ZYBJYKsikGpBlckinNUAqv4z0uht/jZvymxMz4+S9xk5FtsyyfZ7PrCH5/gPt94IzDfn/tSUJREnj7sixeFOUNED4M38jyg4SVk6+BIucshH4Bp32jmXicY2BkYGAA4uzlnbrx/DZfGbhZGEDgeqfWbAT9v4GFgbkByOVgYAKJAgAa6AnTAHicY2BkYGBu+N/AEMPCAAJAkpEBFbACAEcLAm54nGNhYGBgfsnAwMKAwAAOmwD9AAAAAAAAdgDwAVQB0nicY2BkYGBgZQhjYGMAASYg5gJCBob/YD4DABHBAXgAeJxlj01OwzAQhV/6B6QSqqhgh+QFYgEo/RGrblhUavdddN+mTpsqiSPHrdQDcB6OwAk4AtyAO/BIJ5s2lsffvHljTwDc4Acejt8t95E9XDI7cg0XuBeuU38QbpBfhJto41W4Rf1N2MczpsJtdGF5g9e4YvaEd2EPHXwI13CNT+E69S/hBvlbuIk7/Aq30PHqwj7mXle4jUcv9sdWL5xeqeVBxaHJIpM5v4KZXu+Sha3S6pxrW8QmU4OgX0lTnWlb3VPs10PnIhVZk6oJqzpJjMqt2erQBRvn8lGvF4kehCblWGP+tsYCjnEFhSUOjDFCGGSIyujoO1Vm9K+xQ8Jee1Y9zed0WxTU/3OFAQL0z1xTurLSeTpPgT1fG1J1dCtuy56UNJFezUkSskJe1rZUQuoBNmVXjhF6XNGJPyhnSP8ACVpuyAAAAHicY2BigAAuBuyAlZGJkZmRhZGVkY2BsYK1ODM9zxhMGoJJIwYGAFDiBlwA", {
  "referrer": "",
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": null,
  "method": "GET"
}); ;
fetch("https://www.sehuatang.net/static/image/common/user_online.gif", {
  "headers": {
    "sec-ch-ua": "\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"100\", \"Google Chrome\";v=\"100\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"Windows\"",
    "Referer": "https://www.sehuatang.net/data/cache/style_1_common.css?JXX",
    "Referrer-Policy": "strict-origin-when-cross-origin"
  },
  "body": null,
  "method": "GET"
}); ;
fetch("https://www.sehuatang.net/static/image/common/arrwd.gif", {
  "headers": {
    "sec-ch-ua": "\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"100\", \"Google Chrome\";v=\"100\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"Windows\"",
    "Referer": "https://www.sehuatang.net/data/cache/style_1_common.css?JXX",
    "Referrer-Policy": "strict-origin-when-cross-origin"
  },
  "body": null,
  "method": "GET"
}); ;
fetch("https://www.sehuatang.net/template/default/style/t1/nv.png", {
  "headers": {
    "sec-ch-ua": "\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"100\", \"Google Chrome\";v=\"100\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"Windows\"",
    "Referer": "https://www.sehuatang.net/template/default/style/t1/style.css",
    "Referrer-Policy": "strict-origin-when-cross-origin"
  },
  "body": null,
  "method": "GET"
}); ;
fetch("https://www.sehuatang.net/static/image/common/qmenu.png", {
  "headers": {
    "sec-ch-ua": "\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"100\", \"Google Chrome\";v=\"100\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"Windows\"",
    "Referer": "https://www.sehuatang.net/data/cache/style_1_common.css?JXX",
    "Referrer-Policy": "strict-origin-when-cross-origin"
  },
  "body": null,
  "method": "GET"
}); ;
fetch("https://www.sehuatang.net/template/default/style/t1/nv_a.png", {
  "headers": {
    "sec-ch-ua": "\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"100\", \"Google Chrome\";v=\"100\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"Windows\"",
    "Referer": "https://www.sehuatang.net/template/default/style/t1/style.css",
    "Referrer-Policy": "strict-origin-when-cross-origin"
  },
  "body": null,
  "method": "GET"
}); ;
fetch("https://www.sehuatang.net/template/default/style/t1/search.png", {
  "headers": {
    "sec-ch-ua": "\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"100\", \"Google Chrome\";v=\"100\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"Windows\"",
    "Referer": "https://www.sehuatang.net/template/default/style/t1/style.css",
    "Referrer-Policy": "strict-origin-when-cross-origin"
  },
  "body": null,
  "method": "GET"
}); ;
fetch("https://www.sehuatang.net/static/image/common/search.png", {
  "headers": {
    "sec-ch-ua": "\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"100\", \"Google Chrome\";v=\"100\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"Windows\"",
    "Referer": "https://www.sehuatang.net/data/cache/style_1_common.css?JXX",
    "Referrer-Policy": "strict-origin-when-cross-origin"
  },
  "body": null,
  "method": "GET"
}); ;
fetch("https://www.sehuatang.net/static/image/common/pt_item.png", {
  "headers": {
    "sec-ch-ua": "\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"100\", \"Google Chrome\";v=\"100\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"Windows\"",
    "Referer": "https://www.sehuatang.net/data/cache/style_1_common.css?JXX",
    "Referrer-Policy": "strict-origin-when-cross-origin"
  },
  "body": null,
  "method": "GET"
}); ;
fetch("https://www.sehuatang.net/static/image/common/px.png", {
  "headers": {
    "sec-ch-ua": "\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"100\", \"Google Chrome\";v=\"100\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"Windows\"",
    "Referer": "https://www.sehuatang.net/data/cache/style_1_common.css?JXX",
    "Referrer-Policy": "strict-origin-when-cross-origin"
  },
  "body": null,
  "method": "GET"
}); ;
fetch("https://www.sehuatang.net/static/image/common/arw_r.gif", {
  "headers": {
    "sec-ch-ua": "\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"100\", \"Google Chrome\";v=\"100\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"Windows\"",
    "Referer": "https://www.sehuatang.net/data/cache/style_1_common.css?JXX",
    "Referrer-Policy": "strict-origin-when-cross-origin"
  },
  "body": null,
  "method": "GET"
}); ;
fetch("https://www.sehuatang.net/static/image/common/scrolltop.png", {
  "headers": {
    "sec-ch-ua": "\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"100\", \"Google Chrome\";v=\"100\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"Windows\"",
    "Referer": "https://www.sehuatang.net/data/cache/style_1_common.css?JXX",
    "Referrer-Policy": "strict-origin-when-cross-origin"
  },
  "body": null,
  "method": "GET"
}); ;
fetch("chrome-extension://efaidnbmnnnibpcajpcglclefindmkaj/data/js/extn-utils.html", {
  "headers": {
    "upgrade-insecure-requests": "1"
  },
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": null,
  "method": "GET"
}); ;
fetch("chrome-extension://efaidnbmnnnibpcajpcglclefindmkaj/data/js/extn-utils.js", {
  "headers": {
    "if-modified-since": "Wed, 19 Jan 2022 03:25:10 GMT",
    "if-none-match": "\"OSJi/YJo8fBQXYbL1wr2LG3mOKM=\""
  },
  "referrer": "",
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": null,
  "method": "GET"
}); ;
fetch("https://www.sehuatang.net/favicon.ico", {
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": null,
  "method": "GET"
});

**Comment by Khaleesi01** [comment]
我是直接复制完就粘贴到青龙的环境变量中了，没有修改

**Comment by xjasonlyu** [comment]
你点了fetch all as nodejs fetch了吧…

**Comment by Khaleesi01** [comment]
> 你点了copy all as nodejs fetch了吧…

啊，还真是，要这眼睛有何用。 十分感谢，可以运行了！

**Comment by Jieoz** [comment]
> > 你点了copy all as nodejs fetch了吧…
> 
> 啊，还真是，要这眼睛有何用。 十分感谢，可以运行了！

老哥可以细说步骤吗？我这里复制签到时验证码连接的 `copy all as nodejs fetch` 跑不起来

```
色花堂签到
## 开始执行... 2023-02-20 13:38:43

Traceback (most recent call last):
  File "/ql/data/scripts/raw_main_daysign.py", line 139, in <module>
    main()
  File "/ql/data/scripts/raw_main_daysign.py", line 111, in main
    cookies = retrieve_cookies_from_fetch('FETCH_98TANG')
  File "/ql/data/scripts/raw_main_daysign.py", line 77, in retrieve_cookies_from_fetch
    cookie_str = parse_fetch(os.getenv(env))['headers']['cookie']
  File "/ql/data/scripts/raw_main_daysign.py", line 72, in parse_fetch
    exec(s, {
  File "<string>", line 5
    "sec-ch-ua": "\Chromium\;v=\110\, \Not A(Brand\;v=\24\, \Google Chrome\;v=\110\",
                 ^
SyntaxError: unterminated string literal (detected at line 5)


## 执行结束... 2023-02-20 13:38:47  耗时 4 秒
```
